kind: pipeline
type: docker
name: default

steps:
  - name: frontend
    image: node:12-alpine
    commands:
      - npm ci
      - npm run test
      - npm run lint
  - name: build
    image: node:12-alpine
    commands:
      - npm ci
      - npm run build:client
      - npm run build:server
