kind: pipeline
name: default

steps:
  - name: build
    image: node:12-alpine
    command: npm ci
  - name: lint
    command: npm run lint
  - name: test
    command: npm run test
trigger:
  ref:
    - refs/pull/*/head
