kind: pipeline
name: default

steps:
  - name: lint
    image: build
    commands:
      - npm ci
      - npm run lint
  - name: test
    image: build
    commands:
      - npm ci
      - npm run test
trigger:
  ref:
    - refs/pull/*/head
