kind: pipeline
name: default

steps:
  - name: frontend
    image: node:12-alpine
    commands:
      - npm ci
      - npm run test
      - npm run lint
trigger:
  ref:
    - refs/heads/master
    - refs/heads/**
    - refs/pull/*/head
