kind: pipeline
name: default

pipeline:
  build:
    image: node:12-alpine
    commands: npm ci
  lint:
    image: node:12-alpine
    command: npm run lint
  test:
    image: node:12-alpine
    command: npm run test
trigger:
  ref:
    - refs/pull/*/head
