kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:12-alpine
    commands:
      - npm ci
      - ls -la
  - name: build
    image: node:12-alpine
    commands:
      - npm run build:client
      - npm run build:server
      - ls -la
  - name: testing
    image: node:12-alpine
    group: testing
    commands:
      - ls
      - npm run test
  - name: lint
    image: node:12-alpine
    group: testing
    commands:
      - npm run lint
  - name: publish
    image: plugins/docker
    settings:
      repo: lithium366/react-typescript
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
